services:
  scraper:
    image: parallax-trade/scraper
    container_name: 'parallax-trade-scraper'
    profiles:
      - scraper
    build:
      context: ../submodules/scraper
      dockerfile: Dockerfile.local
    volumes:
      - ../submodules/scraper:/app
    environment:
      APP_ENV: ${APP_ENV}
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_PORT: ${MARIADB_PORT}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      SCRAPER_PORT: ${SCRAPER_PORT}
      KOREA_PRICE_SOURCE_URL: ${KOREA_PRICE_SOURCE_URL}
      INTERNATIONAL_PRICE_SOURCE_URL_PREFIX: ${INTERNATIONAL_PRICE_SOURCE_URL_PREFIX}
      INTERNATIONAL_PRICE_SOURCE_URL_POSTFIX: ${INTERNATIONAL_PRICE_SOURCE_URL_POSTFIX}
    ports:
      - '${SCRAPER_PORT}:${SCRAPER_PORT}'
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    restart: on-failure
